<?php

use App\Palindrome;
use PHPUnit\Framework\TestCase;

/**
 * Class PalindromeTest
 */
class PalindromeTest extends TestCase
{
	protected Palindrome $polindrome;

	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->polindrome = new Palindrome();
	}

	/**
	 * @test
	 * @group PalindromeTest
	 *
	 * sequence: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33, 44, 55, 66, 77, 88, 99, 101, 111
	 * 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33, 44, 55, 66, 77, 88, 99, 101, 111, 121, 131, 141, 151, 161, 171, 181, 191, 202
	 */
	public function is_even_return_true_when_passed_22()
	{
		$this->assertEquals(true, $this->polindrome->isEven(22));
	}
}